# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: 
    Build workingDir: '6.14.4'
    pool:
      vmImage: ubuntu-latest
    steps:
    

- task: NodeTool@0
  inputs:
    versionSpec: '10.19.0'
  displayName: 'install Node.js'

- script : | 
      npm install
      npm run build
  displayName: 'npm install and build '

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  inputs:
    targetPath:  '$(Pipeline.Workspace)'
    publishLocation: 'Pipeline'